services:
  pgvector:
    image: pgvector/pgvector:pg16
    platform: linux/amd64
    container_name: pgvector-container
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports:
      - "6024:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
